version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm start

    ports:
      - "4000:4000"
    env_file:
      - ./.env.dev
    networks:
      - app-network
    depends_on:
      - api
  api:
    build:
      context: ./scraper
      dockerfile: Dockerfile.api
    command: python app.py
    expose:
      - "5001"
    env_file:
      - .env.dev
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    

    
  
  